#!/usr/bin/env python3
# ===================================================================
# PROOF SCRIPT — auto-generated by Proof-Carrying Data Analyst
# Question : What was February 2026 revenue in USD?
# Spec     : {"months": ["2026-02"], "region": null, "currency": "USD", "metric": "sum"}
# Run      : python Q03.py [optional/path/to/data]
# Needs    : Python 3.9+, pandas
# ===================================================================

# ------------------------------------------------- cleaning library (verbatim)
"""
Single source of truth for data cleaning.

IMPORTANT: this file's source code is copied VERBATIM into every generated
proof script, so it must only import stdlib + pandas and must not import
anything else from this package. That is what makes each answer re-runnable
by a judge with nothing but `python script.py`.
"""
import re
from pathlib import Path

import pandas as pd

US_FMT, EU_FMT = "MDY", "DMY"
SOURCE_DATE_FORMAT = {"us_shop": US_FMT, "eu_shop": EU_FMT}  # legacy: undocumented


def parse_amount(text, currency_col, source):
    """Return (value, currency). value is None when missing/unparseable."""
    t = "" if text is None or (isinstance(text, float) and pd.isna(text)) else str(text).strip()
    cur = None
    if "€" in t or "EUR" in t.upper():
        cur = "EUR"
    elif "$" in t or "USD" in t.upper():
        cur = "USD"
    col = "" if currency_col is None or (isinstance(currency_col, float) and pd.isna(currency_col)) \
        else str(currency_col).strip().upper()
    if col:
        if cur and cur != col:
            return None, "CONFLICT"
        cur = col
    num = re.sub(r"[^0-9.,\-]", "", t)
    if not num:
        return None, cur
    if cur == "EUR" or (cur is None and source == "eu_shop"):
        num = num.replace(".", "").replace(",", ".")      # 1.234,50 -> 1234.50
    else:
        num = num.replace(",", "")                        # 1,234.50 -> 1234.50
    try:
        return float(num), cur
    except ValueError:
        return None, cur


def parse_date(text, source):
    """Return (date_a, date_b, ambiguous). date_a == date_b when unambiguous."""
    m = re.fullmatch(r"\s*(\d{1,2})[/-](\d{1,2})[/-](\d{4})\s*", str(text))
    if not m:
        try:
            d = pd.Timestamp(str(text)).normalize()
            return d, d, False
        except Exception:
            return pd.NaT, pd.NaT, False
    x, y, yr = int(m.group(1)), int(m.group(2)), int(m.group(3))

    def mk(mo, dy):
        try:
            return pd.Timestamp(year=yr, month=mo, day=dy)
        except ValueError:
            return pd.NaT

    fmt = SOURCE_DATE_FORMAT.get(source)
    if fmt == US_FMT:
        d = mk(x, y); return d, d, False
    if fmt == EU_FMT:
        d = mk(y, x); return d, d, False
    # undocumented format: infer only when one reading is impossible
    dmy, mdy = mk(y, x), mk(x, y)
    if pd.isna(dmy):
        return mdy, mdy, False
    if pd.isna(mdy) or dmy == mdy:
        return dmy, dmy, False
    return dmy, mdy, True


def load_fx(data_dir):
    fx = pd.read_csv(Path(data_dir) / "fx_rates.csv", dtype=str)
    return {(r.month, r.from_ccy, r.to_ccy): float(r.rate) for r in fx.itertuples()}


def to_usd(value, currency, month, fx):
    if value is None or pd.isna(value):
        return float("nan")
    if currency == "USD":
        return float(value)
    rate = fx.get((month, currency, "USD"))
    return float("nan") if rate is None else float(value) * rate


def load_orders(data_dir):
    raw = pd.read_csv(Path(data_dir) / "orders.csv", dtype=str, keep_default_na=False)
    n_raw = len(raw)
    raw = raw.drop_duplicates()                           # exact re-exports
    n_exact_dupes = n_raw - len(raw)
    fx = load_fx(data_dir)
    recs = []
    for r in raw.itertuples(index=False):
        val, cur = parse_amount(r.amount, r.currency, r.source_system)
        da, db, amb = parse_date(r.order_date, r.source_system)
        month_a = da.strftime("%Y-%m") if not pd.isna(da) else None
        month_b = db.strftime("%Y-%m") if not pd.isna(db) else None
        recs.append({
            "order_id": r.order_id, "customer_id": r.customer_id, "source": r.source_system,
            "amount_native": val, "currency": cur,
            "date_a": da, "date_b": db, "date_ambiguous": amb,
            "month_a": month_a, "month_b": month_b,
            "amount_missing": val is None,
            "currency_unknown": cur not in ("USD", "EUR"),
            "amount_usd": to_usd(val, cur, month_a, fx) if cur in ("USD", "EUR") else float("nan"),
        })
    df = pd.DataFrame(recs)
    # semantic duplicates: same order, different text formatting -> same parsed values
    n_before = len(df)
    df = df.drop_duplicates(subset=["order_id", "customer_id", "amount_native", "currency", "month_a"])
    n_exact_dupes += n_before - len(df)
    # same order_id, different content after parsing = key conflict (kept, but flagged)
    key_conflicts = df[df.duplicated("order_id", keep=False)]["order_id"].unique().tolist()
    df = df.drop_duplicates("order_id", keep="first").reset_index(drop=True)
    df["key_conflict"] = df["order_id"].isin(key_conflicts)
    df.attrs.update(n_raw=n_raw, n_exact_dupes=n_exact_dupes, key_conflicts=key_conflicts)
    return df


def load_customers(data_dir):
    c = pd.read_csv(Path(data_dir) / "customers.csv", dtype=str, keep_default_na=False)
    regions = c.groupby("customer_id")["region"].agg(lambda s: sorted(set(s)))
    return regions.to_dict()          # customer_id -> [region, ...] (len>1 = contradiction)


def load_refunds(data_dir):
    return pd.read_csv(Path(data_dir) / "refunds.csv", dtype={"order_id": str, "currency": str})


def scope_mask(df, months, region=None, cust_regions=None):
    """Rows whose month is in scope under EVERY possible date reading, customer in region."""
    m = df["month_a"].isin(months) & df["month_b"].isin(months)
    if region:
        m &= df["customer_id"].map(lambda c: (cust_regions or {}).get(c, []) == [region])
    return m

# ------------------------------------------------------------------ query
import json, sys
DATA_DIR = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(__file__).resolve().parent.parent / "data"
MONTHS, REGION, CURRENCY, METRIC = ['2026-02'], None, 'USD', 'sum'

orders = load_orders(DATA_DIR)
cust = load_customers(DATA_DIR)
fx = load_fx(DATA_DIR)
scope = orders[scope_mask(orders, MONTHS, REGION, cust)]

def in_ccy(row_usd, month):
    if CURRENCY == "USD":
        return row_usd
    return row_usd / fx[(month, CURRENCY, "USD")]

usable = scope[scope["amount_usd"].notna()].copy()
usable["amt"] = [in_ccy(v, m) for v, m in zip(usable["amount_usd"], usable["month_a"])]

if METRIC == "count":
    value, unit = int(scope["order_id"].nunique()), "orders"
elif METRIC == "sum":
    value, unit = round(float(usable["amt"].sum()), 2), CURRENCY
elif METRIC == "avg":
    value, unit = round(float(usable["amt"].mean()), 2), CURRENCY
elif METRIC == "net_sum":
    refunds = load_refunds(DATA_DIR)
    month_of = dict(zip(usable["order_id"], usable["month_a"]))
    refunds = refunds[refunds["order_id"].isin(month_of)]
    ref_total = sum(in_ccy(to_usd(a, c, month_of[o], fx), month_of[o])
                    for a, c, o in zip(refunds["amount"], refunds["currency"], refunds["order_id"]))
    value, unit = round(float(usable["amt"].sum()) - round(ref_total, 2), 2), CURRENCY
else:
    raise SystemExit("unknown metric")

print(json.dumps({"value": value, "unit": unit, "rows_in_scope": int(len(scope)),
                  "rows_used": int(len(usable)) if METRIC != "count" else int(len(scope)),
                  "rows_excluded_missing_amount": int(len(scope) - len(usable))}))
