"""
CODE GENERATOR — emits a STANDALONE proof script per answer.

The script embeds cleaning.py verbatim, reads the raw CSVs, prints one JSON
line. A judge can run `python runs/Q01.py` (or `python Q01.py /path/to/data`)
with nothing installed except pandas, and must get the same number.
"""
import inspect
import json

from . import cleaning

HEADER = '''#!/usr/bin/env python3
# ===================================================================
# PROOF SCRIPT — auto-generated by Proof-Carrying Data Analyst
# Question : {question}
# Spec     : {spec}
# Run      : python {qid}.py [optional/path/to/data]
# Needs    : Python 3.9+, pandas
# ===================================================================
'''

BODY = '''
# ------------------------------------------------------------------ query
import json, sys
DATA_DIR = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(__file__).resolve().parent.parent / "data"
MONTHS, REGION, CURRENCY, METRIC = {months!r}, {region!r}, {currency!r}, {metric!r}

orders = load_orders(DATA_DIR)
cust = load_customers(DATA_DIR)
fx = load_fx(DATA_DIR)
scope = orders[scope_mask(orders, MONTHS, REGION, cust)]

def in_ccy(row_usd, month):
    if CURRENCY == "USD":
        return row_usd
    return row_usd / fx[(month, CURRENCY, "USD")]

usable = scope[scope["amount_usd"].notna()].copy()
usable["amt"] = [in_ccy(v, m) for v, m in zip(usable["amount_usd"], usable["month_a"])]

if METRIC == "count":
    value, unit = int(scope["order_id"].nunique()), "orders"
elif METRIC == "sum":
    value, unit = round(float(usable["amt"].sum()), 2), CURRENCY
elif METRIC == "avg":
    value, unit = round(float(usable["amt"].mean()), 2), CURRENCY
elif METRIC == "net_sum":
    refunds = load_refunds(DATA_DIR)
    month_of = dict(zip(usable["order_id"], usable["month_a"]))
    refunds = refunds[refunds["order_id"].isin(month_of)]
    ref_total = sum(in_ccy(to_usd(a, c, month_of[o], fx), month_of[o])
                    for a, c, o in zip(refunds["amount"], refunds["currency"], refunds["order_id"]))
    value, unit = round(float(usable["amt"].sum()) - round(ref_total, 2), 2), CURRENCY
else:
    raise SystemExit("unknown metric")

print(json.dumps({{"value": value, "unit": unit, "rows_in_scope": int(len(scope)),
                  "rows_used": int(len(usable)) if METRIC != "count" else int(len(scope)),
                  "rows_excluded_missing_amount": int(len(scope) - len(usable))}}))
'''


def generate(qid, spec):
    lib = inspect.getsource(cleaning)
    public = {k: spec[k] for k in ("months", "region", "currency", "metric")}
    return (HEADER.format(question=spec["question"], spec=json.dumps(public), qid=qid)
            + "\n# ------------------------------------------------- cleaning library (verbatim)\n"
            + lib + BODY.format(**public))
